<script setup lang="ts">
import { computed, ref } from 'vue'
import { router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import type { CarteraItem } from '../../types'

const props = defineProps<{ cartera: { items: CarteraItem[] }, filters: { edificio_id?: string | null, departamento_id?: string | null }, edificios: Array<{ id: string, nombre: string }>, departamentos: Array<{ id: string, edificioId: string, codigo: string, nombre: string }> }>()
const edificioId = ref(props.filters.edificio_id ?? '')
const departamentoId = ref(props.filters.departamento_id ?? '')
const departments = computed(() => props.departamentos.filter(item => !edificioId.value || item.edificioId === edificioId.value).map(item => ({ label: `${item.codigo} · ${item.nombre}`, value: item.id })))
const reload = () => router.get(route('cartera.index'), { edificio_id: edificioId.value || undefined, departamento_id: departamentoId.value || undefined }, { preserveState: true, preserveScroll: true, replace: true })
</script>

<template>
  <UDashboardPanel id="cartera"><template #header><UDashboardNavbar title="Cartera preliminar"><template #leading><UDashboardSidebarCollapse /></template><template #right><UButton icon="i-lucide-hand-coins" label="Registrar pago" @click="router.visit(route('pagos.create'))" /></template></UDashboardNavbar></template><template #body><div class="flex h-full flex-col gap-5 p-4 sm:p-6"><UAlert color="info" description="La cartera se deriva de cargos, aplicaciones y saldo a favor. No admite edición manual." icon="i-lucide-info" variant="subtle" /><div class="grid gap-3 md:grid-cols-2"><USelect v-model="edificioId" :items="[{ label: 'Todos los edificios', value: '' }, ...edificios.map(item => ({ label: item.nombre, value: item.id }))]" size="xl" @update:model-value="departamentoId = ''; reload()" /><USelect v-model="departamentoId" :items="[{ label: 'Todos los departamentos', value: '' }, ...departments]" size="xl" @update:model-value="reload()" /></div><div class="overflow-x-auto rounded-xl border border-default"><table class="w-full min-w-5xl text-left text-sm"><thead class="bg-elevated/50 text-xs uppercase tracking-wide text-muted"><tr><th class="p-3">Departamento</th><th class="p-3">Propietario(s)</th><th class="p-3 text-right">Cargos</th><th class="p-3 text-right">Pagos</th><th class="p-3 text-right">Pendiente</th><th class="p-3 text-right">Favor</th><th class="p-3 text-right">Neto</th><th class="p-3"></th></tr></thead><tbody class="divide-y divide-default"><tr v-for="item in cartera.items" :key="item.departamentoId"><td class="p-3"><p>{{ item.departamento }}</p><p class="text-xs text-muted">{{ item.edificio }}</p></td><td class="p-3">{{ item.propietarios.map(owner => owner.nombre).join(', ') || 'Sin titular vigente' }}</td><td class="p-3 text-right font-mono">${{ item.cargosTotales }}</td><td class="p-3 text-right font-mono">${{ item.pagosAplicados }}</td><td class="p-3 text-right font-mono">${{ item.saldoPendiente }}</td><td class="p-3 text-right font-mono">${{ item.saldoFavor }}</td><td class="p-3 text-right font-mono font-semibold">${{ item.saldoNeto }}</td><td class="p-3 text-right"><UButton icon="i-lucide-plus" label="Pago" size="xs" variant="outline" @click="router.visit(route('pagos.create', { edificio_id: item.edificioId, departamento_id: item.departamentoId }))" /></td></tr><tr v-if="!cartera.items.length"><td class="p-8 text-center text-muted" colspan="8">No hay saldos pendientes ni saldos a favor.</td></tr></tbody></table></div></div></template></UDashboardPanel>
</template>
