<script setup lang="ts">
import { computed, ref } from 'vue'
import { router, usePage } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import PlanMantenimientoPreventivoForm from '../../components/operaciones/PlanMantenimientoPreventivoForm.vue'
import type { ContratoOperacionOption, EdificioOperacionOption, ElementoOperacionOption, PlanMantenimientoPreventivo, PlanMantenimientoPreventivoFormData, ProveedorOperacionOption } from '../../types'

const props = defineProps<{ plan: PlanMantenimientoPreventivo, edificios: EdificioOperacionOption[], torres: ElementoOperacionOption[], pisos: ElementoOperacionOption[], departamentos: ElementoOperacionOption[], parqueaderos: ElementoOperacionOption[], bodegas: ElementoOperacionOption[], proveedores: ProveedorOperacionOption[], contratos: ContratoOperacionOption[] }>()
const page = usePage(); const loading = ref(false)
const errors = computed<Record<string, string>>(() => Object.fromEntries(Object.entries(page.props.errors ?? {}).map(([field, error]) => [field, Array.isArray(error) ? String(error[0]) : String(error)])))
const initial = computed<PlanMantenimientoPreventivoFormData>(() => ({ edificio_id: props.plan.edificioId, codigo: props.plan.codigo, titulo: props.plan.titulo, descripcion: props.plan.descripcion, prioridad: props.plan.prioridad, unidad_recurrencia: props.plan.unidadRecurrencia, intervalo_recurrencia: props.plan.intervaloRecurrencia, dias_anticipacion: props.plan.diasAnticipacion, torre_id: props.plan.torreId ?? '', piso_id: props.plan.pisoId ?? '', departamento_id: props.plan.departamentoId ?? '', parqueadero_id: props.plan.parqueaderoId ?? '', bodega_id: props.plan.bodegaId ?? '', ubicacion_detalle: props.plan.ubicacionDetalle ?? '', proveedor_id: props.plan.proveedorId ?? '', contrato_id: props.plan.contratoId ?? '' }))
const formOptions = computed(() => ({ ...props, proveedores: props.plan.proveedor && !props.proveedores.some(item => item.proveedorId === props.plan.proveedorId) ? [...props.proveedores, props.plan.proveedor] : props.proveedores, contratos: props.plan.contrato && !props.contratos.some(item => item.id === props.plan.contratoId) ? [...props.contratos, props.plan.contrato] : props.contratos, currentLocation: props.plan.ubicacion ?? null }))
const submit = (data: PlanMantenimientoPreventivoFormData) => { const { edificio_id: _building, ...payload } = data; router.put(route('mantenimiento-preventivo.update', [props.plan.edificioId, props.plan.id]), { ...payload, updated_at: props.plan.updatedAt }, { onStart: () => { loading.value = true }, onFinish: () => { loading.value = false } }) }
</script>

<template><UDashboardPanel id="mantenimiento-edit"><template #header><UDashboardNavbar :title="`Editar · ${plan.codigo}`"><template #leading><UDashboardSidebarCollapse /></template></UDashboardNavbar></template><template #body><div class="mx-auto w-full max-w-4xl p-4 sm:p-6"><UAlert v-if="errors.estado || errors.updatedAt" class="mb-5" color="error" :description="errors.estado || errors.updatedAt" icon="i-lucide-circle-alert" variant="subtle" /><UCard><PlanMantenimientoPreventivoForm :key="plan.updatedAt || plan.id" v-bind="formOptions" :initial="initial" :errors="errors" :loading="loading" :lock-scope="true" submit-label="Actualizar plan" @cancel="router.visit(route('mantenimiento-preventivo.show', [plan.edificioId, plan.id]))" @submit="submit" /></UCard></div></template></UDashboardPanel></template>
