<script setup lang="ts">
import { computed, ref } from 'vue'
import { router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import type { BitacoraPlanMantenimiento, EstadoOcurrenciaMantenimientoPreventivo, PlanMantenimientoPreventivo, TipoEventoPlanMantenimiento, UnidadRecurrenciaMantenimiento } from '../../types'
import { useBuildingPermissions } from '../../composables/useBuildingPermissions'

const props = defineProps<{ plan: PlanMantenimientoPreventivo }>()
const { can } = useBuildingPermissions(); const loading = ref(false); const actionError = ref(''); const statusOpen = ref(false); const omitOpen = ref(false); const selectedOccurrence = ref(''); const nextDate = ref(''); const omitReason = ref('')
const canProgram = computed(() => can('mantenimiento_preventivo.programar', props.plan.edificioId))
const unitLabels: Record<UnidadRecurrenciaMantenimiento, string> = { diaria: 'día(s)', semanal: 'semana(s)', mensual: 'mes(es)', anual: 'año(s)' }
const occurrenceLabels: Record<EstadoOcurrenciaMantenimientoPreventivo, string> = { pendiente: 'Pendiente', generada: 'Generada', bloqueada: 'Bloqueada', omitida: 'Omitida' }
const occurrenceColors: Record<EstadoOcurrenciaMantenimientoPreventivo, 'info' | 'success' | 'error' | 'neutral'> = { pendiente: 'info', generada: 'success', bloqueada: 'error', omitida: 'neutral' }
const eventLabels: Record<TipoEventoPlanMantenimiento, string> = { creacion: 'Plan creado', cambio_datos: 'Configuración actualizada', activacion: 'Plan activado', pausa: 'Plan pausado', generacion: 'Orden generada', bloqueo: 'Ocurrencia bloqueada', reintento: 'Reintento solicitado', omision: 'Ocurrencia omitida' }
const formatDate = (value: string | null) => value ? new Date(value).toLocaleString('es-EC') : 'No disponible'
const detailText = (entry: BitacoraPlanMantenimiento) => { const detail = entry.detalle ?? {}; if (typeof detail.motivo === 'string') return detail.motivo; if (typeof detail.resumen === 'string') return detail.resumen; if (typeof detail.ordenNumero === 'string') return `Orden ${detail.ordenNumero} generada para ${detail.fechaProgramada}`; if (typeof detail.proximaFechaProgramada === 'string') return `Próxima fecha: ${detail.proximaFechaProgramada}`; if (detail.cambios) return 'Se actualizó la configuración futura del plan.'; return 'Evento registrado con detalle estructurado.' }
const requestOptions = { preserveScroll: true, onStart: () => { loading.value = true; actionError.value = '' }, onFinish: () => { loading.value = false }, onError: (errors: Record<string, string>) => { actionError.value = String(Object.values(errors)[0] ?? 'No fue posible completar la acción.') } }
const openStatus = () => { nextDate.value = ''; actionError.value = ''; statusOpen.value = true }
const changeStatus = () => router.patch(route('mantenimiento-preventivo.status', [props.plan.edificioId, props.plan.id]), { estado: props.plan.estado === 'activo' ? 'inactivo' : 'activo', proxima_fecha_programada: props.plan.estado === 'activo' ? null : nextDate.value }, { ...requestOptions, onSuccess: () => { statusOpen.value = false } })
const retry = (id: string) => router.post(route('mantenimiento-preventivo.occurrences.retry', [props.plan.edificioId, props.plan.id, id]), {}, requestOptions)
const openOmit = (id: string) => { selectedOccurrence.value = id; omitReason.value = ''; actionError.value = ''; omitOpen.value = true }
const omit = () => router.patch(route('mantenimiento-preventivo.occurrences.omit', [props.plan.edificioId, props.plan.id, selectedOccurrence.value]), { motivo: omitReason.value }, { ...requestOptions, onSuccess: () => { omitOpen.value = false } })
</script>

<template>
  <UDashboardPanel id="mantenimiento-show">
    <template #header><UDashboardNavbar :title="plan.codigo"><template #leading><UDashboardSidebarCollapse /></template></UDashboardNavbar></template>
    <template #body><div class="mx-auto flex w-full max-w-6xl flex-col gap-6 p-4 sm:p-6">
      <UAlert v-if="actionError" color="error" :description="actionError" icon="i-lucide-circle-alert" variant="subtle" />
      <div class="flex flex-wrap justify-end gap-2"><UButton color="neutral" icon="i-lucide-list" label="Todos los planes" variant="outline" @click="router.visit(route('mantenimiento-preventivo.index'))" /><UButton v-if="plan.estado === 'inactivo' && can('mantenimiento_preventivo.gestionar', plan.edificioId)" color="neutral" icon="i-lucide-pencil" label="Editar" variant="outline" @click="router.visit(route('mantenimiento-preventivo.edit', [plan.edificioId, plan.id]))" /><UButton v-if="canProgram" :color="plan.estado === 'activo' ? 'warning' : 'primary'" :icon="plan.estado === 'activo' ? 'i-lucide-pause' : 'i-lucide-play'" :label="plan.estado === 'activo' ? 'Pausar plan' : 'Activar plan'" @click="openStatus" /></div>
      <UCard><template #header><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-sm text-muted">{{ plan.edificio || plan.edificioId }}</p><h1 class="mt-1 text-2xl font-semibold text-highlighted">{{ plan.titulo }}</h1><p class="mt-2 font-mono text-sm text-primary">{{ plan.codigo }}</p></div><UBadge :color="plan.estado === 'activo' ? 'success' : 'neutral'" :label="plan.estado === 'activo' ? 'Activo' : 'Inactivo'" size="lg" variant="subtle" /></div></template><p class="whitespace-pre-line text-sm leading-6 text-muted">{{ plan.descripcion }}</p><dl class="mt-6 grid gap-5 border-t border-default pt-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs uppercase text-muted">Recurrencia</dt><dd class="mt-1">Cada {{ plan.intervaloRecurrencia }} {{ unitLabels[plan.unidadRecurrencia] }}</dd></div><div><dt class="text-xs uppercase text-muted">Anticipación</dt><dd class="mt-1">{{ plan.diasAnticipacion }} día(s)</dd></div><div><dt class="text-xs uppercase text-muted">Próxima fecha</dt><dd class="mt-1 font-medium">{{ plan.proximaFechaProgramada || 'Sin programar' }}</dd></div><div><dt class="text-xs uppercase text-muted">Ubicación</dt><dd class="mt-1">{{ plan.ubicacion?.etiqueta || plan.ubicacion?.detalle || 'No disponible' }}</dd></div></dl></UCard>
      <div class="grid gap-6 lg:grid-cols-2"><UCard><template #header><p class="font-semibold text-highlighted">Proveedor predeterminado</p></template><div v-if="plan.proveedor" class="space-y-1 text-sm"><p class="font-medium">{{ plan.proveedor.nombre }}</p><p class="text-muted">{{ plan.proveedor.identificacion }}</p><p v-if="plan.contrato" class="pt-2 font-mono text-xs text-primary">{{ plan.contrato.referencia }} · {{ plan.contrato.objeto }}</p></div><p v-else class="text-sm text-muted">Las órdenes se generarán sin proveedor ni contrato.</p></UCard><UCard><template #header><p class="font-semibold text-highlighted">Alcance financiero</p></template><p class="text-sm text-muted">Este plan sólo genera órdenes operativas reportadas. No asigna responsables ni crea gastos, cuentas por pagar, desembolsos o movimientos de tesorería.</p></UCard></div>
      <UCard><template #header><div><p class="font-semibold text-highlighted">Ocurrencias</p><p class="mt-1 text-xs text-muted">Cada fecha conserva su resultado y admite como máximo una orden.</p></div></template><div v-if="plan.ocurrencias?.length" class="divide-y divide-default"><div v-for="occurrence in plan.ocurrencias" :key="occurrence.id" class="grid gap-3 py-4 first:pt-0 last:pb-0 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div><div class="flex flex-wrap items-center gap-2"><p class="font-medium">{{ occurrence.fechaProgramada }}</p><UBadge :color="occurrenceColors[occurrence.estado]" :label="occurrenceLabels[occurrence.estado]" variant="subtle" /></div><p v-if="occurrence.motivo" class="mt-2 text-sm text-error">{{ occurrence.motivo }}</p><p v-if="occurrence.procesadaAt" class="mt-1 text-xs text-muted">Procesada {{ formatDate(occurrence.procesadaAt) }}</p></div><div class="flex flex-wrap gap-2 md:justify-end"><UButton v-if="occurrence.orden" color="neutral" icon="i-lucide-clipboard-wrench" :label="occurrence.orden.numero" variant="outline" @click="router.visit(route('operaciones.show', [plan.edificioId, occurrence.orden!.id]))" /><UButton v-if="occurrence.estado === 'bloqueada' && canProgram" icon="i-lucide-refresh-cw" label="Reintentar" :loading="loading" @click="retry(occurrence.id)" /><UButton v-if="occurrence.estado === 'bloqueada' && canProgram" color="neutral" icon="i-lucide-skip-forward" label="Omitir" variant="outline" @click="openOmit(occurrence.id)" /></div></div></div><p v-else class="text-sm text-muted">El plan todavía no tiene ocurrencias materializadas.</p></UCard>
      <UCard><template #header><div><p class="font-semibold text-highlighted">Bitácora del plan</p><p class="mt-1 text-xs text-muted">Historial append-only de decisiones humanas y ejecuciones del sistema.</p></div></template><div v-if="plan.bitacora?.length" class="relative ml-2 border-l border-default pl-6"><div v-for="entry in plan.bitacora" :key="entry.id" class="relative pb-6 last:pb-0"><span class="absolute -left-[1.78rem] top-1 size-3 rounded-full border-2 border-default bg-primary"></span><p class="font-medium">{{ eventLabels[entry.tipo] }}</p><p class="mt-1 text-sm text-muted">{{ detailText(entry) }}</p><p class="mt-1 text-xs text-dimmed">{{ entry.actorNombre }} · {{ formatDate(entry.createdAt) }}</p></div></div><p v-else class="text-sm text-muted">No hay eventos registrados.</p></UCard>
    </div></template>
  </UDashboardPanel>
  <UModal v-model:open="statusOpen" :close="!loading" :dismissible="!loading" :title="plan.estado === 'activo' ? 'Pausar plan' : 'Activar plan'" :description="plan.estado === 'activo' ? 'La pausa no cancela órdenes ya generadas y descarta la ocurrencia bloqueada vigente.' : 'La nueva fecha será el ancla de la recurrencia.'"><template #body><UFormField v-if="plan.estado === 'inactivo'" label="Primera fecha programada" required><UInput v-model="nextDate" class="w-full" type="date" /></UFormField></template><template #footer><div class="flex w-full justify-end gap-3"><UButton color="neutral" label="Volver" variant="outline" :disabled="loading" @click="statusOpen = false" /><UButton :color="plan.estado === 'activo' ? 'warning' : 'primary'" :label="plan.estado === 'activo' ? 'Confirmar pausa' : 'Activar plan'" :disabled="plan.estado === 'inactivo' && !nextDate" :loading="loading" @click="changeStatus" /></div></template></UModal>
  <UModal v-model:open="omitOpen" :close="!loading" :dismissible="!loading" title="Omitir ocurrencia" description="La decisión queda auditada y la programación avanza a la siguiente fecha."><template #body><UFormField label="Motivo" required><UTextarea v-model="omitReason" :rows="3" maxlength="2000" /></UFormField></template><template #footer><div class="flex w-full justify-end gap-3"><UButton color="neutral" label="Volver" variant="outline" :disabled="loading" @click="omitOpen = false" /><UButton color="warning" label="Omitir ocurrencia" :disabled="!omitReason.trim()" :loading="loading" @click="omit" /></div></template></UModal>
</template>
