<script setup lang="ts">
import { ref } from 'vue'
import { router } from '@inertiajs/vue3'
import { route } from 'ziggy-js'
import TarifaForm from '../../components/conceptos/TarifaForm.vue'
import type { ConceptoCobro, TarifaConcepto, TarifaConceptoFormData } from '../../types'

const props = defineProps<{ concepto: ConceptoCobro }>()
const tariffOpen = ref(false)
const loading = ref(false)
const errors = ref<Record<string, string>>({})
const labels = { ordinario: 'Ordinario', extraordinario: 'Extraordinario', consumo: 'Consumo', multa: 'Multa', interes: 'Interés', otro: 'Otro', valor_fijo: 'Valor fijo', por_alicuota: 'Por alícuota', porcentaje: 'Porcentaje', por_consumo: 'Por consumo', manual: 'Manual', mensual: 'Mensual', trimestral: 'Trimestral', semestral: 'Semestral', anual: 'Anual', unico: 'Único' }
const formatDate = (date: string) => new Intl.DateTimeFormat('es', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`))
const rateText = (tarifa: TarifaConcepto) => tarifa.porcentaje !== null ? `${tarifa.porcentaje}%` : tarifa.valor !== null ? `${tarifa.valor}${tarifa.unidad ? ` / ${tarifa.unidad}` : ''}` : 'Configuración manual'
const stateLabel = (tarifa: TarifaConcepto) => tarifa.estado === 'vigente' ? 'Vigente' : tarifa.estado === 'programada' ? 'Programada' : 'Finalizada'
const openTariff = () => { errors.value = {}; tariffOpen.value = true }
const submitTariff = (data: TarifaConceptoFormData) => router.post(route('conceptos.tarifas.store', [props.concepto.edificioId, props.concepto.id]), data, { preserveScroll: true, onStart: () => { loading.value = true }, onSuccess: () => { tariffOpen.value = false }, onError: responseErrors => { errors.value = responseErrors }, onFinish: () => { loading.value = false } })
</script>

<template>
  <UDashboardPanel id="conceptos-show"><template #header><UDashboardNavbar :title="`${concepto.codigo} · ${concepto.nombre}`"><template #leading><UDashboardSidebarCollapse /></template><template #right><UButton color="neutral" icon="i-lucide-pencil" label="Editar concepto" variant="outline" :ui="{ label: 'hidden sm:inline' }" @click="router.visit(route('conceptos.edit', [concepto.edificioId, concepto.id]))" /></template></UDashboardNavbar></template><template #body><div class="mx-auto flex w-full max-w-6xl flex-col gap-6 p-4 sm:p-6">
    <UCard><template #header><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-muted">Información general</p><h1 class="mt-1 text-xl font-semibold text-highlighted">{{ concepto.nombre }}</h1><p class="mt-1 text-sm text-muted">{{ concepto.edificio }}</p></div><UBadge :color="concepto.estado === 'activo' ? 'success' : 'neutral'" :label="concepto.estado === 'activo' ? 'Activo' : 'Inactivo'" variant="subtle" /></div></template><dl class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs uppercase tracking-wide text-muted">Tipo</dt><dd class="mt-1 text-sm text-highlighted">{{ labels[concepto.tipo] }}</dd></div><div><dt class="text-xs uppercase tracking-wide text-muted">Periodicidad</dt><dd class="mt-1 text-sm text-highlighted">{{ labels[concepto.periodicidad] }}</dd></div><div><dt class="text-xs uppercase tracking-wide text-muted">Forma de cálculo</dt><dd class="mt-1 text-sm text-highlighted">{{ labels[concepto.formaCalculo] }}</dd></div><div><dt class="text-xs uppercase tracking-wide text-muted">Código</dt><dd class="mt-1 font-mono text-sm text-highlighted">{{ concepto.codigo }}</dd></div></dl><p v-if="concepto.descripcion" class="mt-5 border-t border-default pt-4 text-sm text-muted">{{ concepto.descripcion }}</p></UCard>
    <UCard><template #header><div class="flex flex-wrap items-center justify-between gap-4"><div><p class="font-medium text-highlighted">Tarifas y vigencias</p><p class="mt-1 text-xs text-muted">Las tarifas finalizadas son historial; una nueva vigencia cierra de forma segura la tarifa abierta anterior.</p></div><UButton icon="i-lucide-plus" label="Nueva tarifa" :disabled="concepto.estado !== 'activo'" @click="openTariff" /></div></template><div v-if="concepto.tarifaVigente" class="mb-5 rounded-xl border border-primary/30 bg-primary/5 p-4"><p class="text-xs uppercase tracking-wide text-muted">Tarifa vigente</p><p class="mt-1 font-mono text-xl font-semibold text-highlighted">{{ rateText(concepto.tarifaVigente) }}</p><p class="mt-1 text-sm text-muted">Desde {{ formatDate(concepto.tarifaVigente.fechaInicio) }} · {{ concepto.tarifaVigente.alcance === 'todo_el_edificio' ? 'Todo el edificio' : `${concepto.tarifaVigente.departamentos.length} departamento(s)` }}</p></div><UAlert v-else color="neutral" description="No existe una tarifa vigente para este concepto." icon="i-lucide-circle-dollar-sign" variant="subtle" /><div class="mt-5 overflow-x-auto"><table class="w-full min-w-4xl text-left text-sm"><thead class="border-b border-default text-xs uppercase tracking-wide text-muted"><tr><th class="px-3 py-3 font-medium">Vigencia</th><th class="px-3 py-3 font-medium">Configuración</th><th class="px-3 py-3 font-medium">Alcance</th><th class="px-3 py-3 font-medium">Estado</th><th class="px-3 py-3 font-medium">Observación</th></tr></thead><tbody class="divide-y divide-default"><tr v-for="tarifa in concepto.tarifas" :key="tarifa.id"><td class="px-3 py-3 text-muted">{{ formatDate(tarifa.fechaInicio) }}<span v-if="tarifa.fechaFin"> – {{ formatDate(tarifa.fechaFin) }}</span><span v-else> – {{ tarifa.estado === 'programada' ? 'programada' : 'vigente' }}</span></td><td class="px-3 py-3"><p class="font-mono text-highlighted">{{ rateText(tarifa) }}</p><p v-if="tarifa.montoTotal" class="text-xs text-muted">Total: {{ tarifa.montoTotal }} · {{ tarifa.numeroCuotas }} cuota(s)</p><p v-if="tarifa.baseCalculo" class="text-xs text-muted">Base: {{ tarifa.baseCalculo.replace('_', ' ') }}</p></td><td class="px-3 py-3 text-muted">{{ tarifa.alcance === 'todo_el_edificio' ? 'Todo el edificio' : tarifa.departamentos.map(item => item.codigo).join(', ') }}</td><td class="px-3 py-3"><UBadge :color="tarifa.estado === 'vigente' ? 'success' : tarifa.estado === 'programada' ? 'primary' : 'neutral'" :label="stateLabel(tarifa)" variant="subtle" /></td><td class="px-3 py-3 text-muted">{{ tarifa.observacion || '—' }}</td></tr><tr v-if="!concepto.tarifas?.length"><td colspan="5" class="px-3 py-10 text-center text-muted">Aún no hay tarifas registradas.</td></tr></tbody></table></div></UCard>
  </div></template></UDashboardPanel>
  <UModal v-model:open="tariffOpen" :close="!loading" :dismissible="!loading" title="Nueva tarifa" :description="`La nueva vigencia se registrará para ${concepto.codigo} sin eliminar el historial.`"><template #body><TarifaForm :forma-calculo="concepto.formaCalculo" :tipo="concepto.tipo" :departamentos="concepto.departamentosDisponibles ?? []" :errors="errors" :loading="loading" @submit="submitTariff" @cancel="tariffOpen = false" /></template></UModal>
</template>
